platform: linux

image_resource:
  type: docker-image
  source: {repository: limaofeng/gradle-alpine}
    
inputs:
  - name: demo-actuator
  
outputs:
  - name: resource-app
  
run:
  path: ./demo-actuator/ci/build.sh